spring:
  datasource:
    url: jdbc:h2://mem/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.jpa.sql: DEBUG